### ISSUE TITLE
Missing version.rc file for pyinstaller when using pyinstaller-versionfile

### ISSUE THREAD

**Issue by crbon** [sayyid5416/pyinstaller#16]
Hi

I'm using `pyinstaller-versionfile` in a prior to `pyinstaller` to generate the `version.rc` file. When the github action runs, the version.rc file is not present for `pyinstaller`.

What am I doing wrong?

Here is an example of my actions.yml file

```yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pyinstaller_build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Install dependencies
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller-versionfile

      # Add step to create version file before PyInstaller build
      - name: Create Version File
        run: create-version-file version_metadata.yml --outfile version.rc

      - name: LS version.rc (before pyinstaller)
        run: |
          ls ./
          mkdir test

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11.7'
          pyinstaller_ver: '==6.3.0'
          spec: 'presenterfocus.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'PresenterFocus'
          options: --onefile --windowed --icon "icon.png" --name "PresenterFocus"

      - name: LS version.rc (after pyinstaller)
        run: |
          ls ./
          # the version.rc and test dir are not present here
```
