### ISSUE TITLE
--version-file option

### ISSUE THREAD

**Issue by andreabz** [sayyid5416/pyinstaller#28]
Currently, --version-file is not listed in the pyinstaller options supported by this GitHub Action. Is this going to change?

**Comment by sayyid5416** [comment]
@andreabz I'll need more info. Can you elaborate more about what you want!

**Comment by andreabz** [comment]
Sorry for being not clear, I'll try again!
I'd like if your GitHub actions would support the pyinstaller --version-file option described [here](https://pyinstaller.org/en/stable/usage.html#windows-specific-options).

This option automatically includes the information provided in a predefined file, usually - or at least in my case - obtained by using [pyinstaller-versionfile](https://pypi.org/project/pyinstaller-versionfile/) on a yml file, and makes them visible in the Windows property pane of the app.

I find this option useful to know in advance the name, description and version of the application I'm going to run, or to easily provide context for bugs reported by other users.

Thanks.

**Comment by sayyid5416** [comment]
@andreabz Test with `version-file` branch, and report back if it's working or not.
```yaml
uses: sayyid5416/pyinstaller@version-file
```

**Comment by andreabz** [comment]
> @andreabz Test with `version-file` branch, and report back if it's working or not.
> 
> ```
> uses: sayyid5416/pyinstaller@version-file
> ```

Thanks. However, running this Action

`
name: Python Pyinstaller

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pyinstaller-build:
    runs-on: [ windows-latest ]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@version-file
        with:
          python_ver: '3.6'
          pyinstaller_ver: '==5.13.2'
          spec: 'myapp.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'myapp'
          options: --onefile, --name "myapp", --windowed, --version-file "file_version_info.txt"
`

 I got this error:

`
Run python "D:\a\_actions\sayyid5416\pyinstaller\version-file/src/checks.py"
Traceback (most recent call last):
  File "D:\a\_actions\sayyid5416\pyinstaller\version-file/src/checks.py", line 1, in <module>
    from actions import *
  File "D:\a\_actions\sayyid5416\pyinstaller\version-file\src\actions.py", line 2, in <module>
    from typing import Literal
ImportError: cannot import name 'Literal'
`

Shouldn't be dependencies installed and included in the Action itself?

**Comment by sayyid5416** [comment]
You are using python version 3.6, try to increase it

**Comment by sayyid5416** [comment]
@andreabz Have this worked for you?

**Comment by ZeroMarker** [comment]
I got same issue. Finally I find out why.
I edit workflow on github.com , save it.
Then I pull the code, add tag, push to trigger workflow.
I got this issue, the workflow seems always work on 3.6 python version.
The local workflow is wrong, so I delete it, clone & tag & push, it's work.

**Comment by sayyid5416** [comment]
@ZeroMarker so everything works fine now?

**Comment by ZeroMarker** [comment]
The final step is not work.
GitHub Action Output
```ps1
Warning: No files were found with the provided path: src\Notepad.spec. No artifacts will be uploaded.
Run echo "✔️ Executable **_(Notepad)_** uploaded successfully" >> $GITHUB_STEP_SUMMARY
```
My Action yaml
```yaml
name: Build and Release

on:
  push:
    tags:
      - 'v*'
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: 3.9
          spec: 'src/notepad.py'
          upload_exe_with_name: 'My executable'
          options: --onefile, --name "Notepad", --windowed,
```
The artifact is generated, but not uploaded.
How to fix this?
